//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int deductionID { get; set; }
        public Nullable<int> payrollID { get; set; }
        public string deductionType { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> deductionDate { get; set; }
    
        public virtual Payroll Payroll { get; set; }
    }
}
