//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Expenses = new HashSet<Expense>();
            this.Expenses1 = new HashSet<Expense>();
            this.Grievances = new HashSet<Grievance>();
            this.Leaves = new HashSet<Leave>();
            this.Leaves1 = new HashSet<Leave>();
            this.Payrolls = new HashSet<Payroll>();
            this.Schedulings = new HashSet<Scheduling>();
            this.TaskAttachments = new HashSet<TaskAttachment>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskNotifications = new HashSet<TaskNotification>();
            this.TaskReports = new HashSet<TaskReport>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.WorkflowTables = new HashSet<WorkflowTable>();
        }
    
        public int employeeID { get; set; }
        public int payrollID { get; set; }
        public int managerID { get; set; }
        public int clientID { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string preferredName { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string identificationNumber { get; set; }
        public string maritalStatus { get; set; }
        public string nationality { get; set; }
        public string emailAddress { get; set; }
        public string phoneNumber { get; set; }
        public string emergencyContactName { get; set; }
        public string emergencyContactPhone { get; set; }
        public string emergencyContactRelationship { get; set; }
        public string position { get; set; }
        public string jobTitle { get; set; }
        public string department { get; set; }
        public System.DateTime hireDate { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public string employmentStatus { get; set; }
        public string employmentType { get; set; }
        public int workHoursPerWeek { get; set; }
        public double salary { get; set; }
        public double hourlyRate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public string country { get; set; }
        public string officeLocation { get; set; }
        public string profilePicture { get; set; }
        public string password { get; set; }
        public bool active { get; set; }
        public Nullable<decimal> OvertimeRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grievance> Grievances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scheduling> Schedulings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAttachment> TaskAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNotification> TaskNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskReport> TaskReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowTable> WorkflowTables { get; set; }
    }
}
