//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrievanceAction
    {
        public int ActionID { get; set; }
        public Nullable<int> GrievanceID { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual Grievance Grievance { get; set; }
    }
}
