//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EngineeringClubHREntities4 : DbContext
    {
        public EngineeringClubHREntities4()
            : base("name=EngineeringClubHREntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addition> Additions { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GrievanceLog> GrievanceLogs { get; set; }
        public virtual DbSet<Grievance> Grievances { get; set; }
        public virtual DbSet<GrievanceStatu> GrievanceStatus { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Scheduling> Schedulings { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TaskAttachment> TaskAttachments { get; set; }
        public virtual DbSet<TaskComment> TaskComments { get; set; }
        public virtual DbSet<TaskNotification> TaskNotifications { get; set; }
        public virtual DbSet<TaskReport> TaskReports { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TeamChat> TeamChats { get; set; }
        public virtual DbSet<TimeSchedule> TimeSchedules { get; set; }
        public virtual DbSet<WorkflowTable> WorkflowTables { get; set; }
    }
}
