//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.Deductions = new HashSet<Deduction>();
        }
    
        public int payrollID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<System.DateTime> payPeriodStart { get; set; }
        public Nullable<System.DateTime> payPeriodEnd { get; set; }
        public Nullable<double> totalHoursWorked { get; set; }
        public Nullable<double> totalOvertimeWorked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduction> Deductions { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
