//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNotification
    {
        public int NotificationId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> NotifiedTo { get; set; }
        public string NotificationText { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
