//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReport
    {
        public int ReportId { get; set; }
        public Nullable<int> GeneratedBy { get; set; }
        public string ReportContent { get; set; }
        public Nullable<System.DateTime> GeneratedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
