//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringClubHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowTable
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ManagerFirstName { get; set; }
        public string ManagerLastName { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<int> LeaveOrExpenseID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ManagerActionDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Status Status { get; set; }
    }
}
